### ISSUE TITLE
GUIDs should be more robust

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#32]
I have items in [this feed](https://captnemo.in/npci-rss-feeds/feeds/upi.xml) where `links` aren't available ([see website](https://www.npci.org.in/what-we-do/upi/circular)).

```xml
    
    <item>
      <title><![CDATA[UPI OC 144 - Please get in touch with your bank.]]></title>
      <link></link>
      
      <description><![CDATA[UPI OC 144 - <b>Please get in touch with your bank.</b>]]></description>
      <content:encoded><![CDATA[UPI OC 144 - <b>Please get in touch with your bank.</b>]]></content:encoded>
      <guid isPermaLink="true"></guid>
      
    </item>
```

In such cases, the guid is empty, and this will cause issues with some feedreaders (since GUIDs for multiple no-link items will collide). A better solution would be to generate a GUID from a hash of title/link/content.

`rss-bridge` for eg uses `urn:sha1:<sha1_hash>` where the hash is generated accordingly.

**Comment by r7kamura** [comment]
Hmm, I hadn't considered the case where the URL is blank before, but you're right.

It appears that rss-bridge uses the URL if available, or SHA1 of the title and content if not.

https://github.com/RSS-Bridge/rss-bridge/blob/91283f3a625e0e51f7bec4bd2b31ee9bf9f75001/formats/AtomFormat.php#L47-L54
