### ISSUE TITLE
Customizable title for feeds

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#37]
In continuation to https://github.com/r7kamura/weneedfeed/commit/897ce7dd83e02d42535f44ad0268dc7f4d0161c6, the title for all the feeds, both on the HTML as well as the OPML XML should be customizable via the YAML.

**Comment by r7kamura** [comment]
I agree with you.

I used the title "Weneedfeed" for now, but was hoping for a more appropriate text for each YAML. I had to make weneedfeed.yml have a key called `pages:`, not just an array, for this to happen.
