### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#44]
A lot of websites will decline requests coming from a Faraday user-agent, and weneedfeed fails quitely.

curl "https://www.npci.org.in/what-we-do/upi/circular" for eg.

A simple `user_agent` configuration in the YAML file should do.

**Comment by r7kamura** [comment]
Thank you @captn3m0, I understand the issue of Faraday User-Agent being rejected.

If that is the case, I would think that simply adding a fixed User-Agent (e.g. `User-Agent:  Weneedfeed`) by default would solve the problem. I am wondering if adding the ability to customize the User-Agent just for this issue might be a bit too complex. What do you think?
