### ISSUE TITLE
Configure Faraday Adapter

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#47]
I was attempting to use weneedfeed against https://github.com/lwthiker/curl-impersonate and it needs configuring the default faraday adapter, which needs a patch to `scraping.rb`.

It would be nice if this was configurable as a string in the configuration itself. I'm not sure how the dependency resolution for the adapter would work in this case though.

**Comment by r7kamura** [comment]
Since `Weneedfeed::Scraping.faraday_connection` is public, how about changing adapter like this?

```ruby
Weneedfeed::Scraping.faraday_connection.adapter :some_faraday_addapter
```

https://github.com/r7kamura/weneedfeed/blob/856d67150ec96c9ed8c7c007cbbdae21f446cb57/lib/weneedfeed/scraping.rb#L12-L19

**Comment by captn3m0** [comment]
Yes, but that still won't work with stock setups, where I want to use the weneedfeed binary.

**Comment by r7kamura** [comment]
Surely, if you want to use `exe/weneedfeed` as is, there is no way to achieve that at this time.
You would have to resolve the gem dependencies of the adapter you are adding as you mentioned, and also, you would have to give the appropriate options to the adapter as well. It seems quite difficult to do that with just a static configuration file 🤔

**Comment by captn3m0** [comment]
Closing this. Will write a wrapper script.
